const LOCAL_IMAGES = new Set([
  '(qp) Chicken Dum Biryani Bowl - 500ml',
  '2pcs Chicken Kurkure Burger',
  'Aloo Paratha',
  'Badam milk shake',
  'Biscoff Cheesecake Slice',
  'Buttermilk',
  'Capsicum Pizza',
  'Chicken 65 Hyderabadi Biryani',
  'Chicken Fried Rice With Chilli Chicken',
  'Chicken Pahari Fresh Steam Momo',
  'Chicken Steam Momo',
  'Chicken Supreme Burger',
  'Chicken Zinger Burger - Classic',
  'Chilli Paneer Dry',
  'Chilli Paneer',
  'Chinese Bhel Tangy Tangra Style',
  'Chinese Rice Box',
  'Chocolate Truffle Cake Pastry Slice',
  'Chocolate Truffle Mini Jar Cake',
  'Chola Bhatura - 2 Pcs',
  'Coke zero can (Bevarages)',
  'Dahi Vada',
  'Dal Makhani Bowl',
  'Egg Fried Rice',
  'Farmhouse Pizza',
  'Hyderabadi Lazeez Bhuna Murgh Biryani (Dum Chicken Biryani)(Spicy)',
  'Iced Coffee',
  'Idly Sambar',
  'Java Chip Frappuccino.',
  'Mango Ice Cream (Medium Fat)',
  'Margehrita Pizza',
  'Masala Dosa',
  'McAloo Tikki Burger',
  'OG Thalaiva Chicken Biryani (Boneless)',
  'Paneer Butter Masala',
  'Paneer biryani',
  'Peppar Barbeque Chicken Pizza',
  'Sabudana Vada (4 pcs) & Green Chutney',
  'Special Chinese Thali',
  'Tava Roti',
  'Tender Coconut Ice Cream',
  'Veg Biryani',
  'Veg Crunchy Momo',
  'Veg Fried Rice With Paneer Chilly',
  'Veg Kurkure Momos',
  'Veg Manchurian',
  'Veg Schezwan Fried Rice',
  'Veg Snacker Burger',
  'Veg momos [6 pieces]',
  'sweetcorn Pizza'
])

export function getFoodImage(name: string, fallbackImage: string): string {
  if (LOCAL_IMAGES.has(name)) {
    return `/images/${name}.avif`
  }
  return fallbackImage
}
