const LOCAL_IMAGES = new Set([
  '(qp) chicken dum biryani bowl - 500ml',
  '2pcs chicken kurkure burger',
  'aloo paratha',
  'badam milk shake',
  'biscoff cheesecake slice',
  'buttermilk',
  'capsicum pizza',
  'chicken 65 hyderabadi biryani',
  'chicken fried rice with chilli chicken',
  'chicken pahari fresh steam momo',
  'chicken steam momo',
  'chicken supreme burger',
  'chicken zinger burger - classic',
  'chilli paneer dry',
  'chilli paneer',
  'chinese bhel tangy tangra style',
  'chinese rice box',
  'chocolate truffle cake pastry slice',
  'chocolate truffle mini jar cake',
  'chola bhatura - 2 pcs',
  'coke zero can (bevarages)',
  'dahi vada',
  'dal makhani bowl',
  'egg fried rice',
  'farmhouse pizza',
  'hyderabadi lazeez bhuna murgh biryani (dum chicken biryani)(spicy)',
  'iced coffee',
  'idly sambar',
  'java chip frappuccino.',
  'mango ice cream (medium fat)',
  'margehrita pizza',
  'masala dosa',
  'mcaloo tikki burger',
  'og thalaiva chicken biryani (boneless)',
  'paneer butter masala',
  'paneer biryani',
  'peppar barbeque chicken pizza',
  'sabudana vada (4 pcs) & green chutney',
  'special chinese thali',
  'tava roti',
  'tender coconut ice cream',
  'veg biryani',
  'veg crunchy momo',
  'veg fried rice with paneer chilly',
  'veg kurkure momos',
  'veg manchurian',
  'veg schezwan fried rice',
  'veg snacker burger',
  'veg momos [6 pieces]',
  'sweetcorn pizza'
])

// Helper map to find exact filename casing from lowercase input
const FILENAME_MAP = new Map([
  ['(qp) chicken dum biryani bowl - 500ml', '(qp) Chicken Dum Biryani Bowl - 500ml'],
  ['2pcs chicken kurkure burger', '2pcs Chicken Kurkure Burger'],
  ['aloo paratha', 'Aloo Paratha'],
  ['badam milk shake', 'Badam milk shake'],
  ['biscoff cheesecake slice', 'Biscoff Cheesecake Slice'],
  ['buttermilk', 'Buttermilk'],
  ['capsicum pizza', 'Capsicum Pizza'],
  ['chicken 65 hyderabadi biryani', 'Chicken 65 Hyderabadi Biryani'],
  ['chicken fried rice with chilli chicken', 'Chicken Fried Rice With Chilli Chicken'],
  ['chicken pahari fresh steam momo', 'Chicken Pahari Fresh Steam Momo'],
  ['chicken steam momo', 'Chicken Steam Momo'],
  ['chicken supreme burger', 'Chicken Supreme Burger'],
  ['chicken zinger burger - classic', 'Chicken Zinger Burger - Classic'],
  ['chilli paneer dry', 'Chilli Paneer Dry'],
  ['chilli paneer', 'Chilli Paneer'],
  ['chinese bhel tangy tangra style', 'Chinese Bhel Tangy Tangra Style'],
  ['chinese rice box', 'Chinese Rice Box'],
  ['chocolate truffle cake pastry slice', 'Chocolate Truffle Cake Pastry Slice'],
  ['chocolate truffle mini jar cake', 'Chocolate Truffle Mini Jar Cake'],
  ['chola bhatura - 2 pcs', 'Chola Bhatura - 2 Pcs'],
  ['coke zero can (bevarages)', 'Coke zero can (Bevarages)'],
  ['dahi vada', 'Dahi Vada'],
  ['dal makhani bowl', 'Dal Makhani Bowl'],
  ['egg fried rice', 'Egg Fried Rice'],
  ['farmhouse pizza', 'Farmhouse Pizza'],
  ['hyderabadi lazeez bhuna murgh biryani (dum chicken biryani)(spicy)', 'Hyderabadi Lazeez Bhuna Murgh Biryani (Dum Chicken Biryani)(Spicy)'],
  ['iced coffee', 'Iced Coffee'],
  ['idly sambar', 'Idly Sambar'],
  ['java chip frappuccino.', 'Java Chip Frappuccino.'],
  ['mango ice cream (medium fat)', 'Mango Ice Cream (Medium Fat)'],
  ['margehrita pizza', 'Margehrita Pizza'],
  ['masala dosa', 'Masala Dosa'],
  ['mcaloo tikki burger', 'McAloo Tikki Burger'],
  ['og thalaiva chicken biryani (boneless)', 'OG Thalaiva Chicken Biryani (Boneless)'],
  ['paneer butter masala', 'Paneer Butter Masala'],
  ['paneer biryani', 'Paneer biryani'],
  ['peppar barbeque chicken pizza', 'Peppar Barbeque Chicken Pizza'],
  ['sabudana vada (4 pcs) & green chutney', 'Sabudana Vada (4 pcs) & Green Chutney'],
  ['special chinese thali', 'Special Chinese Thali'],
  ['tava roti', 'Tava Roti'],
  ['tender coconut ice cream', 'Tender Coconut Ice Cream'],
  ['veg biryani', 'Veg Biryani'],
  ['veg crunchy momo', 'Veg Crunchy Momo'],
  ['veg fried rice with paneer chilly', 'Veg Fried Rice With Paneer Chilly'],
  ['veg kurkure momos', 'Veg Kurkure Momos'],
  ['veg manchurian', 'Veg Manchurian'],
  ['veg schezwan fried rice', 'Veg Schezwan Fried Rice'],
  ['veg snacker burger', 'Veg Snacker Burger'],
  ['veg momos [6 pieces]', 'Veg momos [6 pieces]'],
  ['sweetcorn pizza', 'sweetcorn Pizza']
])

export function getFoodImage(name: string, fallbackImage: string): string {
  const normalizedName = name.toLowerCase().trim()
  
  if (LOCAL_IMAGES.has(normalizedName)) {
    const filename = FILENAME_MAP.get(normalizedName) || name
    return `/images/${filename}.avif`
  }
  
  return fallbackImage
}
