export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  image: string
  category: string
  veg: boolean
  rating: number
}

export interface MenuCategory {
  id: string
  name: string
  count: number
}

export const menuCategories: MenuCategory[] = [
  { id: 'appetizers', name: 'Appetizers', count: 8 },
  { id: 'pizzas', name: 'Pizzas', count: 12 },
  { id: 'burgers', name: 'Burgers', count: 10 },
  { id: 'pastas', name: 'Pastas', count: 6 },
  { id: 'desserts', name: 'Desserts', count: 5 },
  { id: 'beverages', name: 'Beverages', count: 8 },
]

export const menuItems: MenuItem[] = [
  // Appetizers
  {
    id: 'app-1',
    name: 'Garlic Bread',
    description: 'Crispy bread with garlic butter and herbs',
    price: 249,
    image: '/placeholder-food.png',
    category: 'appetizers',
    veg: true,
    rating: 4.5,
  },
  {
    id: 'app-2',
    name: 'Mozzarella Sticks',
    description: 'Golden fried mozzarella with marinara sauce',
    price: 199,
    image: '/placeholder-food.png',
    category: 'appetizers',
    veg: true,
    rating: 4.3,
  },
  {
    id: 'app-3',
    name: 'Chicken Wings',
    description: 'Spicy buffalo wings with blue cheese dip',
    price: 349,
    image: '/placeholder-food.png',
    category: 'appetizers',
    veg: false,
    rating: 4.6,
  },
  {
    id: 'app-4',
    name: 'Spring Rolls',
    description: 'Crispy Asian spring rolls with sweet chili sauce',
    price: 189,
    image: '/placeholder-food.png',
    category: 'appetizers',
    veg: true,
    rating: 4.2,
  },
  {
    id: 'app-5',
    name: 'Calamari Fritti',
    description: 'Tender fried squid with lemon aioli',
    price: 399,
    image: '/placeholder-food.png',
    category: 'appetizers',
    veg: false,
    rating: 4.4,
  },
  {
    id: 'app-6',
    name: 'Bruschetta',
    description: 'Toasted bread with tomato, basil, and olive oil',
    price: 229,
    image: '/placeholder-food.png',
    category: 'appetizers',
    veg: true,
    rating: 4.1,
  },
  {
    id: 'app-7',
    name: 'Samosa Platter',
    description: 'Triangle pastry with spiced potato filling',
    price: 179,
    image: '/placeholder-food.png',
    category: 'appetizers',
    veg: true,
    rating: 4.3,
  },
  {
    id: 'app-8',
    name: 'Chicken Tikka',
    description: 'Marinated chicken cubes with yogurt sauce',
    price: 329,
    image: '/placeholder-food.png',
    category: 'appetizers',
    veg: false,
    rating: 4.5,
  },

  // Pizzas
  {
    id: 'pizza-1',
    name: 'Margherita',
    description: 'Fresh mozzarella, tomato sauce, and basil',
    price: 349,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: true,
    rating: 4.4,
  },
  {
    id: 'pizza-2',
    name: 'Pepperoni',
    description: 'Classic pepperoni with mozzarella cheese',
    price: 399,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: false,
    rating: 4.6,
  },
  {
    id: 'pizza-3',
    name: 'Vegetarian Supreme',
    description: 'Bell peppers, onions, mushrooms, and olives',
    price: 379,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: true,
    rating: 4.3,
  },
  {
    id: 'pizza-4',
    name: 'Meat Lovers',
    description: 'Pepperoni, sausage, bacon, and ham',
    price: 499,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: false,
    rating: 4.7,
  },
  {
    id: 'pizza-5',
    name: 'BBQ Chicken',
    description: 'Grilled chicken with BBQ sauce and red onions',
    price: 429,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: false,
    rating: 4.5,
  },
  {
    id: 'pizza-6',
    name: 'Spicy Paneer',
    description: 'Indian cottage cheese with spicy sauce',
    price: 359,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: true,
    rating: 4.2,
  },
  {
    id: 'pizza-7',
    name: 'Four Cheese',
    description: 'Blend of mozzarella, cheddar, parmesan, and blue cheese',
    price: 449,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: true,
    rating: 4.4,
  },
  {
    id: 'pizza-8',
    name: 'Thai Green Curry',
    description: 'Chicken, green curry sauce, and coconut cream',
    price: 459,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: false,
    rating: 4.3,
  },
  {
    id: 'pizza-9',
    name: 'Mediterranean',
    description: 'Feta cheese, sun-dried tomatoes, olives, and spinach',
    price: 389,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: true,
    rating: 4.5,
  },
  {
    id: 'pizza-10',
    name: 'Tandoori Chicken',
    description: 'Tandoori spiced chicken with cilantro',
    price: 419,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: false,
    rating: 4.6,
  },
  {
    id: 'pizza-11',
    name: 'Truffle Mushroom',
    description: 'Wild mushrooms with truffle oil and goat cheese',
    price: 529,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: true,
    rating: 4.7,
  },
  {
    id: 'pizza-12',
    name: 'Prosciutto & Fig',
    description: 'Italian ham with fig jam and arugula',
    price: 499,
    image: '/placeholder-food.png',
    category: 'pizzas',
    veg: false,
    rating: 4.5,
  },

  // Burgers
  {
    id: 'burger-1',
    name: 'Classic Cheeseburger',
    description: 'Beef patty with cheddar, lettuce, tomato, and mayo',
    price: 279,
    image: '/placeholder-food.png',
    category: 'burgers',
    veg: false,
    rating: 4.3,
  },
  {
    id: 'burger-2',
    name: 'Veggie Burger',
    description: 'Plant-based patty with avocado and sprouts',
    price: 249,
    image: '/placeholder-food.png',
    category: 'burgers',
    veg: true,
    rating: 4.1,
  },
  {
    id: 'burger-3',
    name: 'Double Patty',
    description: 'Two beef patties with double cheese and bacon',
    price: 349,
    image: '/placeholder-food.png',
    category: 'burgers',
    veg: false,
    rating: 4.5,
  },
  {
    id: 'burger-4',
    name: 'Spicy Chicken Burger',
    description: 'Crispy chicken with jalapeños and sriracha mayo',
    price: 299,
    image: '/placeholder-food.png',
    category: 'burgers',
    veg: false,
    rating: 4.4,
  },
  {
    id: 'burger-5',
    name: 'Mushroom Swiss',
    description: 'Beef with sautéed mushrooms and Swiss cheese',
    price: 319,
    image: '/placeholder-food.png',
    category: 'burgers',
    veg: false,
    rating: 4.3,
  },
  {
    id: 'burger-6',
    name: 'Paneer Tikka Burger',
    description: 'Marinated paneer with mint chutney',
    price: 269,
    image: '/placeholder-food.png',
    category: 'burgers',
    veg: true,
    rating: 4.2,
  },
  {
    id: 'burger-7',
    name: 'Bacon Cheddar',
    description: 'Beef with crispy bacon and melted cheddar',
    price: 329,
    image: '/placeholder-food.png',
    category: 'burgers',
    veg: false,
    rating: 4.6,
  },
  {
    id: 'burger-8',
    name: 'Falafel Burger',
    description: 'Crispy falafel with tahini and fresh veggies',
    price: 259,
    image: '/placeholder-food.png',
    category: 'burgers',
    veg: true,
    rating: 4.2,
  },
  {
    id: 'burger-9',
    name: 'Premium Wagyu',
    description: 'Premium Japanese beef with truffle aioli',
    price: 549,
    image: '/placeholder-food.png',
    category: 'burgers',
    veg: false,
    rating: 4.8,
  },
  {
    id: 'burger-10',
    name: 'Classic Veg Stack',
    description: 'Grilled vegetables with hummus and pesto',
    price: 239,
    image: '/placeholder-food.png',
    category: 'burgers',
    veg: true,
    rating: 4.0,
  },

  // Pastas
  {
    id: 'pasta-1',
    name: 'Spaghetti Carbonara',
    description: 'Creamy bacon sauce with parmesan and eggs',
    price: 349,
    image: '/placeholder-food.png',
    category: 'pastas',
    veg: false,
    rating: 4.5,
  },
  {
    id: 'pasta-2',
    name: 'Fettuccine Alfredo',
    description: 'Creamy parmesan and butter sauce',
    price: 329,
    image: '/placeholder-food.png',
    category: 'pastas',
    veg: true,
    rating: 4.4,
  },
  {
    id: 'pasta-3',
    name: 'Penne Arrabbiata',
    description: 'Spicy tomato sauce with garlic and red chili',
    price: 309,
    image: '/placeholder-food.png',
    category: 'pastas',
    veg: true,
    rating: 4.3,
  },
  {
    id: 'pasta-4',
    name: 'Seafood Marinara',
    description: 'Mixed seafood in tomato garlic sauce',
    price: 499,
    image: '/placeholder-food.png',
    category: 'pastas',
    veg: false,
    rating: 4.6,
  },
  {
    id: 'pasta-5',
    name: 'Creamy Mushroom',
    description: 'Wild mushrooms in white cream sauce',
    price: 339,
    image: '/placeholder-food.png',
    category: 'pastas',
    veg: true,
    rating: 4.4,
  },
  {
    id: 'pasta-6',
    name: 'Chicken Parmesan',
    description: 'Breaded chicken with tomato sauce and melted cheese',
    price: 389,
    image: '/placeholder-food.png',
    category: 'pastas',
    veg: false,
    rating: 4.5,
  },

  // Desserts
  {
    id: 'dessert-1',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center',
    price: 199,
    image: '/placeholder-food.png',
    category: 'desserts',
    veg: true,
    rating: 4.7,
  },
  {
    id: 'dessert-2',
    name: 'Cheesecake',
    description: 'Creamy New York style cheesecake',
    price: 179,
    image: '/placeholder-food.png',
    category: 'desserts',
    veg: true,
    rating: 4.5,
  },
  {
    id: 'dessert-3',
    name: 'Tiramisu',
    description: 'Italian dessert with coffee and mascarpone',
    price: 189,
    image: '/placeholder-food.png',
    category: 'desserts',
    veg: true,
    rating: 4.6,
  },
  {
    id: 'dessert-4',
    name: 'Brownie Sundae',
    description: 'Warm brownie with vanilla ice cream',
    price: 159,
    image: '/placeholder-food.png',
    category: 'desserts',
    veg: true,
    rating: 4.4,
  },
  {
    id: 'dessert-5',
    name: 'Mango Sorbet',
    description: 'Refreshing mango ice with fresh mango pieces',
    price: 129,
    image: '/placeholder-food.png',
    category: 'desserts',
    veg: true,
    rating: 4.3,
  },

  // Beverages
  {
    id: 'beverage-1',
    name: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice',
    price: 99,
    image: '/placeholder-food.png',
    category: 'beverages',
    veg: true,
    rating: 4.2,
  },
  {
    id: 'beverage-2',
    name: 'Iced Coffee',
    description: 'Cold brew coffee with ice and cream',
    price: 129,
    image: '/placeholder-food.png',
    category: 'beverages',
    veg: true,
    rating: 4.4,
  },
  {
    id: 'beverage-3',
    name: 'Smoothie Bowl',
    description: 'Berry smoothie with granola and coconut',
    price: 179,
    image: '/placeholder-food.png',
    category: 'beverages',
    veg: true,
    rating: 4.3,
  },
  {
    id: 'beverage-4',
    name: 'Masala Chai',
    description: 'Traditional Indian spiced tea',
    price: 69,
    image: '/placeholder-food.png',
    category: 'beverages',
    veg: true,
    rating: 4.5,
  },
  {
    id: 'beverage-5',
    name: 'Lemonade',
    description: 'Fresh lemon juice with mint and ice',
    price: 89,
    image: '/placeholder-food.png',
    category: 'beverages',
    veg: true,
    rating: 4.1,
  },
  {
    id: 'beverage-6',
    name: 'Iced Tea',
    description: 'Cold brewed tea with lemon',
    price: 79,
    image: '/placeholder-food.png',
    category: 'beverages',
    veg: true,
    rating: 4.0,
  },
  {
    id: 'beverage-7',
    name: 'Lassi',
    description: 'Traditional yogurt drink with cardamom',
    price: 79,
    image: '/placeholder-food.png',
    category: 'beverages',
    veg: true,
    rating: 4.3,
  },
  {
    id: 'beverage-8',
    name: 'Mango Shake',
    description: 'Fresh mango with milk and ice cream',
    price: 119,
    image: '/placeholder-food.png',
    category: 'beverages',
    veg: true,
    rating: 4.4,
  },
]
